Run post_hooks (sh script) on *nixes only
Running `.\rebar.cmd clean` inside the proper dir on Windows will
result in the following error:

```
WARN:  Missing plugins: [covertool]
==> proper (clean)
'.' is not recognized as an internal or external command,
ERROR: Command [clean] failed!
operable program or batch file.
```

Solution:
Run this post hook only on *nixes.